ClassWork 9
Osinin-Andrey/HelloWordProject1 pull request #16
Opened 2023-04-18 10:58 UTC by Osinin-Andrey

ClassWork 9

2023-04-19 05:12 UTC, Pavel-Tsishkevich requested changes

2023-04-19 05:12 UTC, Pavel-Tsishkevich commented on src/by/osinin/classwork/lesson9/doctor/Ambulance.java
> +            Doctor Doctor = getDoctorToPatient(patient);
Имя переменной с маленькой нужно

2023-04-19 12:14 UTC, Osinin-Andrey commented on src/by/osinin/classwork/lesson9/doctor/Ambulance.java
> +            Doctor Doctor = getDoctorToPatient(patient);
@Pavel-Tsishkevich исправил

2023-04-21 12:00 UTC, Pavel-Tsishkevich approved these changes

2023-04-21 14:37 UTC, merged